---
deployment:
  tasks:
    - export DEPLOYPATH=/home/kzzajgkh/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/rsync -av public/ $DEPLOYPATH
    - /bin/rsync -av repositories/kzzador/ $DEPLOYPATH